# Generated by Django 2.2.4 on 2019-11-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20191111_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='image',
            field=models.ImageField(default='default_doc_pro.png', upload_to='Doctor/profile_pics'),
        ),
    ]
