# Generated by Django 2.2.4 on 2019-11-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20191112_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
