# Generated by Django 2.2.4 on 2019-11-12 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_dprofile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dprofile',
            old_name='specialities_opt',
            new_name='specialities',
        ),
    ]
