# Generated by Django 2.2.4 on 2019-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20191112_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprofile',
            name='full_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
