# Generated by Django 2.2.4 on 2019-10-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='maxretailprice',
        ),
        migrations.AddField(
            model_name='product',
            name='sallingprice',
            field=models.IntegerField(default=0),
        ),
    ]
