# Generated by Django 2.2.4 on 2019-11-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191019_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=60)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
