# Generated by Django 2.2.4 on 2019-11-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
